import type { Metadata } from 'next';
import './globals.css';
import localFont from "next/font/local"


const ibmPlexSans = localFont( {
  src: [{ path: './fonts/IBMPlexSans-Regular.ttf', weight: '400', style: 'normal',},
    { path: './fonts/IBMPlexSans-Medium.ttf', weight: '500', style: 'normal',},
    { path: './fonts/IBMPlexSans-SemiBold.ttf', weight: '600', style: 'normal',},
    { path: './fonts/IBMPlexSans-Bold.ttf', weight: '500', style: 'normal',},
  ],
  variable: '--font-ibm-plex-sans',
});

const bebasneue = localFont({
  src: [
    {path: "./fonts/BebasNeue-Regular.ttf", weight: "400", style: "normal"},
  ],
  variable: "--font-bebas-neue"
})

export const metadata: Metadata = {
  title: 'Wise-Library',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.variable} ${bebasneue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
